### ISSUE TITLE
Using theme values from Mongo...

### ISSUE THREAD

**Issue by joetidee** [grovelabs/meteor-less#2]
It would be awesome if this package could allow inclusion of data from Mongo, for example. This way values saved by a user (allowing them to customize the colour of their app.) can be retreived from Mongo and fed into the less output at run- time.

**Comment by cmnjcs** [comment]
Hi @joetidee, want to clarify a little. The way I understand this is: I'm a user of application X. In my user settings, I have the option to change the background color/text color/whatever of the app to some value. That setting is persistent, so if I log out and log in again from some other place, the app will still be the color I set it to.

Is that correct?

**Comment by lourd** [comment]
@joetidee You're misunderstanding what this does. This is a build plugin. Nothing happens at runtime. If you want to do something with Less files in your application you're going to need to use that library yourself.
