### ISSUE TITLE
Windows dev to Linux deploy path issue

### ISSUE THREAD

**Issue by AirBorne04** [grovelabs/meteor-less#4]
I am developing on windows where the import path for less are build with windows \ as file separator, when deploying to a linux machine the meteor project fails to build due to the separator conflict as it is expecting / i guess, but on windows this cant be changed.

**Comment by lourd** [comment]
Hi, thanks for the issue. See my comments in #5. The more general issue here is how to write platform-independent file paths

**Comment by lourd** [comment]
Closed by #5
